name: deploy angular

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: view_secrets
    steps:
      - name: pull git repo
        uses: actions/checkout@v2
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_MAIL}}